AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cognito User Pool for Nova English Learning App'

Resources:
  NovaUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: nova-english-learning-users
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true

  NovaUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref NovaUserPool
      ClientName: nova-english-learning-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

Outputs:
  UserPoolId:
    Description: 'User Pool ID'
    Value: !Ref NovaUserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: 'User Pool Client ID'
    Value: !Ref NovaUserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
